"""!@package base
Classes for Shelly(TM) IoT product family supporting mqtt.

These classes implement the interface between Shelly IoT devices and
the Juham framework. They listen appropriate messages in the juham 
mqtt netwokr  and control their Shelly devices accordingly, as well as 
listen the sensor data generated by Shellys and publish it in the standard
Juham format.

"""
