
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2024-05-17T13:57:25-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5c5416d90255132c3deb77fbe58a5a278c3fc09",
 "version": "2.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
