
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-22T00:13:58+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9bbe486cec5ae83d2eae2c343a984df321ee3647",
 "version": "1.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
