
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-22T13:55:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cbe3d2d2cabf3cc77947b4039f3090fa493caf91",
 "version": "2.37.0rc0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
