
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-22T10:19:09-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "c1d3000956a038cd9ad4164af1bfbb72436cce5d",
 "version": "5.4.35"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
