"""
    EMIL DocumentService

    The EMIL DocumentService API description  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: kontakt@emil.de
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import eis.document
from eis.document.model.upload_docx_template_response_class import UploadDocxTemplateResponseClass


class TestUploadDocxTemplateResponseClass(unittest.TestCase):
    """UploadDocxTemplateResponseClass unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUploadDocxTemplateResponseClass(self):
        """Test UploadDocxTemplateResponseClass"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UploadDocxTemplateResponseClass()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
