def test_setup(smbus2, ht0740):
    switch = ht0740.HT0740()
    switch.on()
    switch.off()
    switch.led.disable()
    switch.switch.disable()
    switch.disable()
    switch.on()
    switch.off()
    switch.led.enable()
    switch.switch.enable()
    switch.enable()
    switch.on()
    switch.off()
