
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-20T19:03:26+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "96bfda00c6bd290297f5e3514ea227c6be4d08b4",
 "version": "1.3.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
