
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-04-12T13:34:00+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e6aae3172da5540d56217c66acd1c219200b02a1",
 "version": "0.2.0+23.ge6aae31"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
