
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-17T21:25:22+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8647c45f001c60e7dbdb2b014b5bf6f00c537ec",
 "version": "1.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
