# Generated by Django 3.1.7 on 2021-10-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
