# Generated by Django 3.1.7 on 2021-10-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0004_auto_20211022_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='actions',
            field=models.JSONField(blank=True, default=dict, help_text='All keys and values in the dictionary must be strings.'),
        ),
    ]
