# Generated by Django 3.1.7 on 2021-10-26 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0007_auto_20211025_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mad_notifications.emailtemplate'),
        ),
    ]
