# Generated by Django 3.2.9 on 2022-08-11 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mad_notifications', '0016_alter_emailtemplate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotificationconfig',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
