# Generated by Django 3.2.9 on 2022-08-13 04:56

from django.db import migrations, models
import django.db.models.deletion
from mad_notifications.settings import notification_settings


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0017_alter_usernotificationconfig_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=notification_settings.EMAIL_TEMPLATE_MODEL),
        ),
    ]
