info = {"message": "fix: OPTIC-720: Fix e.viewsStore.forEach error (#5849)", "commit": "779ee98dd7d67c343a3a5f7f62f7f7581a17051e", "date": "2024/05/08 12:50:08", "branch": "", "version": "1.12.1+0.g779ee98.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
