# Generated by Django 3.1.7 on 2021-10-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0005_auto_20211022_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='All keys and values in the dictionary must be strings.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='actions',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
