# Generated by Django 3.1.7 on 2021-10-26 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0008_auto_20211026_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='from_email',
            field=models.CharField(blank=True, help_text='For example: No Reply <noreply@example.com>', max_length=225, null=True),
        ),
    ]
