# Generated by Django 3.2.9 on 2022-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0011_auto_20211129_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='Email Subject here', help_text='Email Subject', max_length=225),
        ),
    ]
