# Generated by Django 3.2.9 on 2022-03-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0012_emailtemplate_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_email',
            field=models.CharField(blank=True, help_text='For example: No Reply &lt;noreply@example.com&gt;', max_length=225, null=True),
        ),
    ]
