# Generated by Django 4.2.6 on 2024-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mad_notifications", "0018_alter_notification_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="mobile_content",
            field=models.TextField(
                help_text="Notification content for web/email sms, push, etc.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="content",
            field=models.TextField(
                help_text="Notification content for web/email", null=True
            ),
        ),
    ]
