# Generated by Django 4.2.6 on 2024-05-21 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mad_notifications", "0021_notificationtemplate"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailTemplate",
        ),
    ]
