
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-18T12:30:04+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5bd8e2fcb6e38e29e17a294397263fd97306f2ee",
 "version": "1.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
