# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: juno/feeshare/v1/tx.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19juno/feeshare/v1/tx.proto\x12\x10juno.feeshare.v1\x1a\x14gogoproto/gogo.proto\x1a\x1cgoogle/api/annotations.proto"k\n\x13MsgRegisterFeeShare\x12\x18\n\x10\x63ontract_address\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65ployer_address\x18\x02 \x01(\t\x12\x1a\n\x12withdrawer_address\x18\x03 \x01(\t:\x04\xe8\xa0\x1f\x00"\x1d\n\x1bMsgRegisterFeeShareResponse"i\n\x11MsgUpdateFeeShare\x12\x18\n\x10\x63ontract_address\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65ployer_address\x18\x02 \x01(\t\x12\x1a\n\x12withdrawer_address\x18\x03 \x01(\t:\x04\xe8\xa0\x1f\x00"\x1b\n\x19MsgUpdateFeeShareResponse"M\n\x11MsgCancelFeeShare\x12\x18\n\x10\x63ontract_address\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65ployer_address\x18\x02 \x01(\t:\x04\xe8\xa0\x1f\x00"\x1b\n\x19MsgCancelFeeShareResponse2\xc6\x03\n\x03Msg\x12\x98\x01\n\x10RegisterFeeShare\x12%.juno.feeshare.v1.MsgRegisterFeeShare\x1a-.juno.feeshare.v1.MsgRegisterFeeShareResponse".\x82\xd3\xe4\x93\x02("&/juno/feeshare/v1/tx/register_FeeShare\x12\x90\x01\n\x0eUpdateFeeShare\x12#.juno.feeshare.v1.MsgUpdateFeeShare\x1a+.juno.feeshare.v1.MsgUpdateFeeShareResponse",\x82\xd3\xe4\x93\x02&"$/juno/feeshare/v1/tx/update_FeeShare\x12\x90\x01\n\x0e\x43\x61ncelFeeShare\x12#.juno.feeshare.v1.MsgCancelFeeShare\x1a+.juno.feeshare.v1.MsgCancelFeeShareResponse",\x82\xd3\xe4\x93\x02&"$/juno/feeshare/v1/tx/cancel_FeeShareB2Z0github.com/CosmosContracts/juno/x/feeshare/typesb\x06proto3'
)


_MSGREGISTERFEESHARE = DESCRIPTOR.message_types_by_name["MsgRegisterFeeShare"]
_MSGREGISTERFEESHARERESPONSE = DESCRIPTOR.message_types_by_name[
    "MsgRegisterFeeShareResponse"
]
_MSGUPDATEFEESHARE = DESCRIPTOR.message_types_by_name["MsgUpdateFeeShare"]
_MSGUPDATEFEESHARERESPONSE = DESCRIPTOR.message_types_by_name[
    "MsgUpdateFeeShareResponse"
]
_MSGCANCELFEESHARE = DESCRIPTOR.message_types_by_name["MsgCancelFeeShare"]
_MSGCANCELFEESHARERESPONSE = DESCRIPTOR.message_types_by_name[
    "MsgCancelFeeShareResponse"
]
MsgRegisterFeeShare = _reflection.GeneratedProtocolMessageType(
    "MsgRegisterFeeShare",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGREGISTERFEESHARE,
        "__module__": "juno.feeshare.v1.tx_pb2"
        # @@protoc_insertion_point(class_scope:juno.feeshare.v1.MsgRegisterFeeShare)
    },
)
_sym_db.RegisterMessage(MsgRegisterFeeShare)

MsgRegisterFeeShareResponse = _reflection.GeneratedProtocolMessageType(
    "MsgRegisterFeeShareResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGREGISTERFEESHARERESPONSE,
        "__module__": "juno.feeshare.v1.tx_pb2"
        # @@protoc_insertion_point(class_scope:juno.feeshare.v1.MsgRegisterFeeShareResponse)
    },
)
_sym_db.RegisterMessage(MsgRegisterFeeShareResponse)

MsgUpdateFeeShare = _reflection.GeneratedProtocolMessageType(
    "MsgUpdateFeeShare",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGUPDATEFEESHARE,
        "__module__": "juno.feeshare.v1.tx_pb2"
        # @@protoc_insertion_point(class_scope:juno.feeshare.v1.MsgUpdateFeeShare)
    },
)
_sym_db.RegisterMessage(MsgUpdateFeeShare)

MsgUpdateFeeShareResponse = _reflection.GeneratedProtocolMessageType(
    "MsgUpdateFeeShareResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGUPDATEFEESHARERESPONSE,
        "__module__": "juno.feeshare.v1.tx_pb2"
        # @@protoc_insertion_point(class_scope:juno.feeshare.v1.MsgUpdateFeeShareResponse)
    },
)
_sym_db.RegisterMessage(MsgUpdateFeeShareResponse)

MsgCancelFeeShare = _reflection.GeneratedProtocolMessageType(
    "MsgCancelFeeShare",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGCANCELFEESHARE,
        "__module__": "juno.feeshare.v1.tx_pb2"
        # @@protoc_insertion_point(class_scope:juno.feeshare.v1.MsgCancelFeeShare)
    },
)
_sym_db.RegisterMessage(MsgCancelFeeShare)

MsgCancelFeeShareResponse = _reflection.GeneratedProtocolMessageType(
    "MsgCancelFeeShareResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _MSGCANCELFEESHARERESPONSE,
        "__module__": "juno.feeshare.v1.tx_pb2"
        # @@protoc_insertion_point(class_scope:juno.feeshare.v1.MsgCancelFeeShareResponse)
    },
)
_sym_db.RegisterMessage(MsgCancelFeeShareResponse)

_MSG = DESCRIPTOR.services_by_name["Msg"]
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"Z0github.com/CosmosContracts/juno/x/feeshare/types"
    )
    _MSGREGISTERFEESHARE._options = None
    _MSGREGISTERFEESHARE._serialized_options = b"\350\240\037\000"
    _MSGUPDATEFEESHARE._options = None
    _MSGUPDATEFEESHARE._serialized_options = b"\350\240\037\000"
    _MSGCANCELFEESHARE._options = None
    _MSGCANCELFEESHARE._serialized_options = b"\350\240\037\000"
    _MSG.methods_by_name["RegisterFeeShare"]._options = None
    _MSG.methods_by_name[
        "RegisterFeeShare"
    ]._serialized_options = (
        b'\202\323\344\223\002("&/juno/feeshare/v1/tx/register_FeeShare'
    )
    _MSG.methods_by_name["UpdateFeeShare"]._options = None
    _MSG.methods_by_name[
        "UpdateFeeShare"
    ]._serialized_options = (
        b'\202\323\344\223\002&"$/juno/feeshare/v1/tx/update_FeeShare'
    )
    _MSG.methods_by_name["CancelFeeShare"]._options = None
    _MSG.methods_by_name[
        "CancelFeeShare"
    ]._serialized_options = (
        b'\202\323\344\223\002&"$/juno/feeshare/v1/tx/cancel_FeeShare'
    )
    _MSGREGISTERFEESHARE._serialized_start = 99
    _MSGREGISTERFEESHARE._serialized_end = 206
    _MSGREGISTERFEESHARERESPONSE._serialized_start = 208
    _MSGREGISTERFEESHARERESPONSE._serialized_end = 237
    _MSGUPDATEFEESHARE._serialized_start = 239
    _MSGUPDATEFEESHARE._serialized_end = 344
    _MSGUPDATEFEESHARERESPONSE._serialized_start = 346
    _MSGUPDATEFEESHARERESPONSE._serialized_end = 373
    _MSGCANCELFEESHARE._serialized_start = 375
    _MSGCANCELFEESHARE._serialized_end = 452
    _MSGCANCELFEESHARERESPONSE._serialized_start = 454
    _MSGCANCELFEESHARERESPONSE._serialized_end = 481
    _MSG._serialized_start = 484
    _MSG._serialized_end = 938
# @@protoc_insertion_point(module_scope)
