# Generated by Django 4.2.2 on 2024-05-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot_accounts', '0002_agents_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='first_sentence',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
