# Generated by Django 3.1.7 on 2021-10-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0002_notification_action'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='action',
            new_name='actions',
        ),
    ]
