# Generated by Django 3.2.9 on 2022-08-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mad_notifications', '0015_usernotificationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='slug',
            field=models.SlugField(help_text='Unique Template identifier', max_length=225, unique=True),
        ),
    ]
