# Generated by Django 4.2.6 on 2024-05-20 11:37

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("mad_notifications", "0019_notification_mobile_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="from_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Phone number to send this message from.",
                max_length=128,
                null=True,
                region=None,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplate",
            name="mobile_content",
            field=models.TextField(
                blank=True,
                help_text='Templated content for SMS, and Push notification etc. <a href="https://docs.djangoproject.com/en/dev/topics/templates/" target="_target">Refer to docs for more details</a>. Supports HTML',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="content",
            field=models.TextField(
                blank=True,
                help_text='Templated content of the email. <a href="https://docs.djangoproject.com/en/dev/topics/templates/" target="_target">Refer to docs for more details</a>. Supports HTML',
                null=True,
            ),
        ),
    ]
