
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-20T04:13:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd78cbc456c14630f92c0661c0c28e722a39bce7",
 "version": "1.25.0.post0.dev146"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
