
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-21T18:09:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "1d8158a3528a3d828337448bbf1ddffb1e236ec5",
 "version": "1.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
