
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-17T15:05:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "a4aa29f6c2d2251e4b9aaebc1a8d3c5fcbd463bb",
 "version": "2024.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
