
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-22T11:06:21-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7796c632847a203f19b75bb8fa26073bc700e8d3",
 "version": "0.16.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
