
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-19T02:15:37+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4af7b3fbfa2fa119c6b7408d00bbe174ebda42bf",
 "version": "1.4.dev2420"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
