
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-20T21:47:50+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "d9e77c5c2cb939b9c1361bfff79f7a68a518b681",
 "version": "2.36.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
