
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

from __future__ import absolute_import
import json

version_json = '''
{
 "date": "2024-05-16T11:29:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d82ece955c4d85922bd89a38525920eceb160a5",
 "version": "2.4.2.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
