from .infoinsta import Info_Insta
from .chat import GPT
from .ktkt import kt
from .tik_tok import Tik_Tok
from .info_tik import Info_Tik
from .pryer import prayer_times
from .insta import instagram
from .send_te_message import Send_telegram_message
from .search_pinterset import Search_Pinterest