
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-22T10:15:02-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe7d1e0d7995fd295021dbba6e00291b8b587bbe",
 "version": "2.8.9.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
