from noveler.controllers.BaseController import BaseController
from noveler.controllers.ActivityController import ActivityController
from noveler.controllers.AssistantController import AssistantController
from noveler.controllers.AuthorController import AuthorController
from noveler.controllers.BibliographyController import BibliographyController
from noveler.controllers.ChapterController import ChapterController
from noveler.controllers.CharacterController import CharacterController
from noveler.controllers.EventController import EventController
from noveler.controllers.ExportController import ExportController
from noveler.controllers.ImageController import ImageController
from noveler.controllers.LinkController import LinkController
from noveler.controllers.LocationController import LocationController
from noveler.controllers.NoteController import NoteController
from noveler.controllers.OllamaModelController import OllamaModelController
from noveler.controllers.SceneController import SceneController
from noveler.controllers.StoryController import StoryController
from noveler.controllers.SubmissionController import SubmissionController
from noveler.controllers.UserController import UserController





