# Generated by Django 4.2.2 on 2024-05-20 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Connectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connector_name', models.CharField(max_length=60)),
                ('connecting_to', models.CharField(max_length=60)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('token_email', models.CharField(max_length=60, null=True)),
                ('token', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voicebot_accounts.connectortoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=60)),
                ('agent_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('batch', 'Batch')], max_length=20)),
                ('prompt', models.TextField()),
                ('connector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voicebot_accounts.connectors')),
            ],
        ),
    ]
