# Generated by Django 4.2.2 on 2024-05-21 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot_accounts', '0003_agents_first_sentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=60)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('connector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voicebot_accounts.connectors')),
            ],
        ),
    ]
