
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-20T06:45:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "9507b4dc509718e3d122b7925309c563bdbf5ba7",
 "version": "0.18.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
