
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-22T07:43:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "ebcb4e7c00b4a242741a702c527e2a2f1d89ea0e",
 "version": "2.6.85"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
