from typing import Final


class StiVariableType:
    STRING: Final = 'String'
    BOOLEAN: Final = 'Boolean'
    BYTE: Final = 'Byte'
    BYTEARRAY: Final = 'Byte[]'
    CHAR: Final = 'Char'
    DATETIME: Final = 'DateTime'
    DATETIMEOFFSET: Final = 'DateTimeOffset'
    TIMESPAN: Final = 'TimeSpan'
    DECIMAL: Final = 'Decimal'
    DOUBLE: Final = 'Double'
    GUID: Final = 'Guid'
    INT: Final = 'Int'
    INT16: Final = 'Int16'
    SHORT: Final = 'Short'
    INT32: Final = 'Int32'
    INT64: Final = 'Int64'
    LONG: Final = 'Long'
    OBJECT: Final = 'Object'
    SBYTE: Final = 'SByte'
    SINGLE: Final = 'Single'
    UINT16: Final = 'UInt16'
    USHORT: Final = 'UShort'
    UINT: Final = 'UInt'
    UINT32: Final = 'UInt32'
    UINT64: Final = 'UInt64'
    ULONG: Final = 'ULong'
    IMAGE: Final= 'Image'

    BYTE_RANGE: Final = 'ByteRange'
    CHAR_RANGE: Final = 'CharRange'
    DATETIME_RANGE: Final = 'DateTimeRange'
    DECIMAL_RANGE: Final = 'DecimalRange'
    DOUBLE_RANGE: Final = 'DoubleRange'
    FLOAT_RANGE: Final = 'FloatRange'
    GUID_RANGE: Final = 'GuidRange'
    INT_RANGE: Final = 'IntRange'
    LONG_RANGE: Final = 'LongRange'
    SHORT_RANGE: Final = 'ShortRange'
    STRING_RANGE: Final = 'StringRange'
    TIMESPAN_RANGE: Final = 'TimeSpanRange'

    BOOL_LIST: Final = 'BoolList'
    BYTE_LIST: Final = 'ByteList'
    CHAR_LIST: Final = 'CharList'
    DATETIME_LIST: Final = 'DateTimeList'
    DECIMAL_LIST: Final = 'DecimalList'
    DOUBLE_LIST: Final = 'DoubleList'
    FLOAT_LIST: Final = 'FloatList'
    GUID_LIST: Final = 'GuidList'
    INT_LIST: Final = 'IntList'
    LONG_LIST: Final = 'LongList'
    SHORT_LIST: Final = 'ShortList'
    STRING_LIST: Final = 'StringList'
    TIMESPAN_LIST: Final = 'TimeSpanList'