#ifndef NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION_HPP_INCLUDED
#define NETGEN_VERSION "6.2.2403-14-g1dc353d3"
#define NETGEN_VERSION_MAJOR 6
#define NETGEN_VERSION_MINOR 2
#define NETGEN_VERSION_PATCH 2403
#define NETGEN_VERSION_TWEAK 14
#define NETGEN_VERSION_HASH "g1dc353d3"
#endif // NETGEN_VERSION_HPP_INCLUDED
