
# This file was generated by 'versioneer.py' (0.23) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-20T07:53:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d4e3a6e09f53dfea0796ca0276e5e6c8d47038cd",
 "version": "1.25.0.post0.dev153"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
