
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-04-30T01:29:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2bf68aeddf67a13a263f58ea3fc4b45fa898a61e",
 "version": "1.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
