
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-20T09:48:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "10fef1c1135c668783908ce7c576a8126c1f0b7f",
 "version": "2.36.2b1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
