from typing import Optional, Tuple

class GooglePlayAPI:
    def __init__(self, email: str, device_code = "px_7a"): ...
    def login(self, aas_token) -> None: ...
    def details(self, package: str) -> Optional[str]: ...
    def latest_version(self, package: str) -> Optional[Tuple[str, int]]: ...
    def download_url(self, package: str, version: int) -> Optional[str]: ...
    @staticmethod
    def request_aas_token(email: str, oauth_token: str) -> str: ...
