# Code generated by protoc-gen-connect-python 0.1.0.dev2, DO NOT EDIT.
import connect

from client.agent.v1 import agent_pb2 as client_dot_agent_dot_v1_dot_agent__pb2

AgentServiceName = "client.agent.v1.AgentService"


class AgentServiceClient:
    def __init__(self, base_url, *, pool=None, compressor=None, json=False, **opts):
        self._ask = connect.Client(
            pool=pool,
            url=f"{base_url}/{AgentServiceName}/Ask",
            response_type=client_dot_agent_dot_v1_dot_agent__pb2.AskAgentResponse,
            compressor=compressor,
            json=json,
            **opts
        )
        self._heartbeat = connect.Client(
            pool=pool,
            url=f"{base_url}/{AgentServiceName}/Heartbeat",
            response_type=client_dot_agent_dot_v1_dot_agent__pb2.HeartbeatResponse,
            compressor=compressor,
            json=json,
            **opts
        )

    def ask(self, req, **opts):
        return self._ask.call_unary(req, **opts)

    def heartbeat(self, req, **opts):
        return self._heartbeat.call_unary(req, **opts)
