# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from client.agent.v1 import agent_pb2 as client_dot_agent_dot_v1_dot_agent__pb2


class AgentServiceStub(object):
    """Agent service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
                '/client.agent.v1.AgentService/Ask',
                request_serializer=client_dot_agent_dot_v1_dot_agent__pb2.AskAgentRequest.SerializeToString,
                response_deserializer=client_dot_agent_dot_v1_dot_agent__pb2.AskAgentResponse.FromString,
                )
        self.Heartbeat = channel.unary_unary(
                '/client.agent.v1.AgentService/Heartbeat',
                request_serializer=client_dot_agent_dot_v1_dot_agent__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=client_dot_agent_dot_v1_dot_agent__pb2.HeartbeatResponse.FromString,
                )


class AgentServiceServicer(object):
    """Agent service definition
    """

    def Ask(self, request, context):
        """API call will return history of agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=client_dot_agent_dot_v1_dot_agent__pb2.AskAgentRequest.FromString,
                    response_serializer=client_dot_agent_dot_v1_dot_agent__pb2.AskAgentResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=client_dot_agent_dot_v1_dot_agent__pb2.HeartbeatRequest.FromString,
                    response_serializer=client_dot_agent_dot_v1_dot_agent__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'client.agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Agent service definition
    """

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/client.agent.v1.AgentService/Ask',
            client_dot_agent_dot_v1_dot_agent__pb2.AskAgentRequest.SerializeToString,
            client_dot_agent_dot_v1_dot_agent__pb2.AskAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/client.agent.v1.AgentService/Heartbeat',
            client_dot_agent_dot_v1_dot_agent__pb2.HeartbeatRequest.SerializeToString,
            client_dot_agent_dot_v1_dot_agent__pb2.HeartbeatResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
