
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-05-20T12:02:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ab33900cc2e9b8246a79825be11c07c4e6354a3e",
 "version": "2.36.2b2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
