# Generated by Django 4.2.2 on 2024-05-21 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicebot_accounts', '0005_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='phone_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voicebot_accounts.phonenumber'),
        ),
    ]
